
CREATE USER APPUSER IDENTIFIED BY AppUser123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO APPUSER;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW TO APPUSER;

ALTER USER APPUSER ACCOUNT UNLOCK;

ALTER SESSION SET CURRENT_SCHEMA = APPUSER;


-- CENTRO
CREATE TABLE CENTRO (
  ID_CENTRO        NUMBER(10)    NOT NULL,
  NOMBRE           VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_CENTRO PRIMARY KEY (ID_CENTRO)
);

-- ESCUELA
CREATE TABLE ESCUELA (
  ID_ESCUELA       NUMBER(10)     NOT NULL,
  NOMBRE           VARCHAR2(150)  NOT NULL,
  DIRECCION        VARCHAR2(200),
  ACUERDO          VARCHAR2(100),
  CONSTRAINT PK_ESCUELA PRIMARY KEY (ID_ESCUELA)
);

-- DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
  ID_DEPARTAMENTO  NUMBER(10)     NOT NULL,
  NOMBRE           VARCHAR2(100)  NOT NULL,
  CODIGO           NUMBER(10),
  CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID_DEPARTAMENTO)
);

-- MUNICIPIO
CREATE TABLE MUNICIPIO (
  ID_MUNICIPIO                    NUMBER(10)     NOT NULL,
  DEPARTAMENTO_ID_DEPARTAMENTO    NUMBER(10)     NOT NULL,
  NOMBRE                          VARCHAR2(150)  NOT NULL,
  CODIGO                          NUMBER(10),
  CONSTRAINT PK_MUNICIPIO PRIMARY KEY (ID_MUNICIPIO),
  CONSTRAINT FK_MUNI_DEPTO FOREIGN KEY (DEPARTAMENTO_ID_DEPARTAMENTO)
    REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

-- UBICACION (relación ESCUELA - CENTRO)
CREATE TABLE UBICACION (
  ESCUELA_ID_ESCUELA  NUMBER(10) NOT NULL,
  CENTRO_ID_CENTRO    NUMBER(10) NOT NULL,
  CONSTRAINT PK_UBICACION PRIMARY KEY (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO),
  CONSTRAINT FK_UBI_ESC FOREIGN KEY (ESCUELA_ID_ESCUELA) REFERENCES ESCUELA (ID_ESCUELA),
  CONSTRAINT FK_UBI_CEN FOREIGN KEY (CENTRO_ID_CENTRO)   REFERENCES CENTRO (ID_CENTRO)
);

-- =========================================================
--  PREGUNTAS (TEÓRICO) Y PREGUNTAS PRÁCTICO
-- =========================================================

CREATE TABLE PREGUNTAS (
  ID_PREGUNTA     NUMBER(10)      NOT NULL,
  PREGUNTA_TEXTO  VARCHAR2(500)   NOT NULL,
  RESPUESTA       NUMBER(1)       NOT NULL,  -- 1..4 indica la opción correcta
  RES1            VARCHAR2(200)   NOT NULL,
  RES2            VARCHAR2(200)   NOT NULL,
  RES3            VARCHAR2(200)   NOT NULL,
  RES4            VARCHAR2(200),
  CONSTRAINT PK_PREGUNTAS PRIMARY KEY (ID_PREGUNTA),
  CONSTRAINT CK_PREG_RESP CHECK (RESPUESTA BETWEEN 1 AND 4)
);

-- PREGUNTAS_PRACTICO
CREATE TABLE PREGUNTAS_PRACTICO (
  ID_PREGUNTA_PRACTICO  NUMBER(10)     NOT NULL,
  PREGUNTA_TEXTO        VARCHAR2(500)  NOT NULL,
  PUNTEO                NUMBER(5,2)    NOT NULL,
  CONSTRAINT PK_PREG_PRACTICO PRIMARY KEY (ID_PREGUNTA_PRACTICO),
  CONSTRAINT CK_PUNTEO_NONNEG CHECK (PUNTEO >= 0)
);

-- =========================================================
--  CORRELATIVO Y REGISTRO / EXAMEN
-- =========================================================

CREATE TABLE CORRELATIVO (
  ID_CORRELATIVO   NUMBER(10)  NOT NULL,
  FECHA            DATE        NOT NULL,
  NO_EXAMEN        NUMBER(10)  NOT NULL,
  CONSTRAINT PK_CORRELATIVO PRIMARY KEY (ID_CORRELATIVO),
  CONSTRAINT UQ_CORRELATIVO_NO UNIQUE (NO_EXAMEN)
);

-- REGISTRO (solicitante)
CREATE TABLE REGISTRO (
  ID_REGISTRO                               NUMBER(10)     NOT NULL,
  UBICACION_ESCUELA_ID_ESCUELA              NUMBER(10)     NOT NULL,
  UBICACION_CENTRO_ID_CENTRO                NUMBER(10)     NOT NULL,
  MUNICIPIO_ID_MUNICIPIO                    NUMBER(10)     NOT NULL,
  MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO    NUMBER(10)     NOT NULL,
  FECHA                                     DATE           NOT NULL,
  TIPO_TRAMITE                               VARCHAR2(50),
  TIPO_LICENCIA                              VARCHAR2(10),
  NOMBRE_COMPLETO                            VARCHAR2(200),
  GENERO                                     VARCHAR2(20),
  CONSTRAINT PK_REGISTRO PRIMARY KEY (ID_REGISTRO),
  CONSTRAINT FK_REG_UBI_ESC FOREIGN KEY (UBICACION_ESCUELA_ID_ESCUELA, UBICACION_CENTRO_ID_CENTRO)
    REFERENCES UBICACION (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO),
  CONSTRAINT FK_REG_MUNI FOREIGN KEY (MUNICIPIO_ID_MUNICIPIO)
    REFERENCES MUNICIPIO (ID_MUNICIPIO),
  CONSTRAINT FK_REG_DEPTO FOREIGN KEY (MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO)
    REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

-- EXAMEN
CREATE TABLE EXAMEN (
  ID_EXAMEN                                       NUMBER(10)  NOT NULL,
  REGISTRO_ID_ESCUELA                             NUMBER(10)  NOT NULL,
  REGISTRO_ID_CENTRO                              NUMBER(10)  NOT NULL,
  REGISTRO_MUNICIPIO_ID_MUNICIPIO                 NUMBER(10)  NOT NULL,
  REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO NUMBER(10)  NOT NULL,
  REGISTRO_ID_REGISTRO                            NUMBER(10)  NOT NULL,
  CORRELATIVO_ID_CORRELATIVO                      NUMBER(10)  NOT NULL,
  CONSTRAINT PK_EXAMEN PRIMARY KEY (ID_EXAMEN),
  CONSTRAINT FK_EXA_REG   FOREIGN KEY (REGISTRO_ID_REGISTRO) REFERENCES REGISTRO (ID_REGISTRO),
  CONSTRAINT FK_EXA_MUNI  FOREIGN KEY (REGISTRO_MUNICIPIO_ID_MUNICIPIO) REFERENCES MUNICIPIO (ID_MUNICIPIO),
  CONSTRAINT FK_EXA_DEPTO FOREIGN KEY (REGISTRO_MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO),
  CONSTRAINT FK_EXA_UBI FOREIGN KEY (REGISTRO_ID_ESCUELA, REGISTRO_ID_CENTRO)
    REFERENCES UBICACION (ESCUELA_ID_ESCUELA, CENTRO_ID_CENTRO),
  CONSTRAINT FK_EXA_CORR FOREIGN KEY (CORRELATIVO_ID_CORRELATIVO) REFERENCES CORRELATIVO (ID_CORRELATIVO)
);


-- Teórico
CREATE TABLE RESPUESTA_USUARIO (
  ID_RESPUESTA_USUARIO  NUMBER(10)  NOT NULL,
  PREGUNTA_ID_PREGUNTA  NUMBER(10)  NOT NULL,
  EXAMEN_ID_EXAMEN      NUMBER(10)  NOT NULL,
  RESPUESTA             NUMBER(1)   NOT NULL, -- 1..4
  CONSTRAINT PK_RESP_USR PRIMARY KEY (ID_RESPUESTA_USUARIO),
  CONSTRAINT FK_RU_PREG FOREIGN KEY (PREGUNTA_ID_PREGUNTA) REFERENCES PREGUNTAS (ID_PREGUNTA),
  CONSTRAINT FK_RU_EXAM FOREIGN KEY (EXAMEN_ID_EXAMEN)     REFERENCES EXAMEN (ID_EXAMEN),
  CONSTRAINT CK_RU_RANGO CHECK (RESPUESTA BETWEEN 1 AND 4)
);

-- Práctico
CREATE TABLE RESPUESTA_PRACTICO_USUARIO (
  ID_RESPUESTA_PRACTICO                     NUMBER(10)   NOT NULL,
  PREGUNTA_PRACTICO_ID_PREGUNTA_PRACTICO    NUMBER(10)   NOT NULL,
  EXAMEN_ID_EXAMEN                          NUMBER(10)   NOT NULL,
  NOTA                                      NUMBER(6,2)  NOT NULL,
  CONSTRAINT PK_RESP_PRACT PRIMARY KEY (ID_RESPUESTA_PRACTICO),
  CONSTRAINT FK_RP_PREG FOREIGN KEY (PREGUNTA_PRACTICO_ID_PREGUNTA_PRACTICO)
    REFERENCES PREGUNTAS_PRACTICO (ID_PREGUNTA_PRACTICO),
  CONSTRAINT FK_RP_EXAM FOREIGN KEY (EXAMEN_ID_EXAMEN) REFERENCES EXAMEN (ID_EXAMEN),
  CONSTRAINT CK_NOTA_NONNEG CHECK (NOTA >= 0)
);



-- CENTRO
CREATE SEQUENCE SEQ_CENTRO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_CENTRO
BEFORE INSERT ON CENTRO
FOR EACH ROW
WHEN (NEW.ID_CENTRO IS NULL)
BEGIN
  SELECT SEQ_CENTRO.NEXTVAL INTO :NEW.ID_CENTRO FROM DUAL;
END;
/

-- ESCUELA
CREATE SEQUENCE SEQ_ESCUELA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_ESCUELA
BEFORE INSERT ON ESCUELA
FOR EACH ROW
WHEN (NEW.ID_ESCUELA IS NULL)
BEGIN
  SELECT SEQ_ESCUELA.NEXTVAL INTO :NEW.ID_ESCUELA FROM DUAL;
END;
/

-- DEPARTAMENTO
CREATE SEQUENCE SEQ_DEPARTAMENTO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_DEPARTAMENTO
BEFORE INSERT ON DEPARTAMENTO
FOR EACH ROW
WHEN (NEW.ID_DEPARTAMENTO IS NULL)
BEGIN
  SELECT SEQ_DEPARTAMENTO.NEXTVAL INTO :NEW.ID_DEPARTAMENTO FROM DUAL;
END;
/

-- MUNICIPIO
CREATE SEQUENCE SEQ_MUNICIPIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_MUNICIPIO
BEFORE INSERT ON MUNICIPIO
FOR EACH ROW
WHEN (NEW.ID_MUNICIPIO IS NULL)
BEGIN
  SELECT SEQ_MUNICIPIO.NEXTVAL INTO :NEW.ID_MUNICIPIO FROM DUAL;
END;
/

-- PREGUNTAS
CREATE SEQUENCE SEQ_PREGUNTAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_PREGUNTAS
BEFORE INSERT ON PREGUNTAS
FOR EACH ROW
WHEN (NEW.ID_PREGUNTA IS NULL)
BEGIN
  SELECT SEQ_PREGUNTAS.NEXTVAL INTO :NEW.ID_PREGUNTA FROM DUAL;
END;
/

-- PREGUNTAS_PRACTICO
CREATE SEQUENCE SEQ_PREG_PRACT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_PREG_PRACT
BEFORE INSERT ON PREGUNTAS_PRACTICO
FOR EACH ROW
WHEN (NEW.ID_PREGUNTA_PRACTICO IS NULL)
BEGIN
  SELECT SEQ_PREG_PRACT.NEXTVAL INTO :NEW.ID_PREGUNTA_PRACTICO FROM DUAL;
END;
/

-- CORRELATIVO
CREATE SEQUENCE SEQ_CORRELATIVO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_CORRELATIVO
BEFORE INSERT ON CORRELATIVO
FOR EACH ROW
WHEN (NEW.ID_CORRELATIVO IS NULL)
BEGIN
  SELECT SEQ_CORRELATIVO.NEXTVAL INTO :NEW.ID_CORRELATIVO FROM DUAL;
END;
/

-- REGISTRO
CREATE SEQUENCE SEQ_REGISTRO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_REGISTRO
BEFORE INSERT ON REGISTRO
FOR EACH ROW
WHEN (NEW.ID_REGISTRO IS NULL)
BEGIN
  SELECT SEQ_REGISTRO.NEXTVAL INTO :NEW.ID_REGISTRO FROM DUAL;
END;
/

-- EXAMEN
CREATE SEQUENCE SEQ_EXAMEN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_EXAMEN
BEFORE INSERT ON EXAMEN
FOR EACH ROW
WHEN (NEW.ID_EXAMEN IS NULL)
BEGIN
  SELECT SEQ_EXAMEN.NEXTVAL INTO :NEW.ID_EXAMEN FROM DUAL;
END;
/

-- RESPUESTA_USUARIO
CREATE SEQUENCE SEQ_RESP_USR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_RESP_USR
BEFORE INSERT ON RESPUESTA_USUARIO
FOR EACH ROW
WHEN (NEW.ID_RESPUESTA_USUARIO IS NULL)
BEGIN
  SELECT SEQ_RESP_USR.NEXTVAL INTO :NEW.ID_RESPUESTA_USUARIO FROM DUAL;
END;
/

-- RESPUESTA_PRACTICO_USUARIO
CREATE SEQUENCE SEQ_RESP_PRACT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER BI_RESP_PRACT
BEFORE INSERT ON RESPUESTA_PRACTICO_USUARIO
FOR EACH ROW
WHEN (NEW.ID_RESPUESTA_PRACTICO IS NULL)
BEGIN
  SELECT SEQ_RESP_PRACT.NEXTVAL INTO :NEW.ID_RESPUESTA_PRACTICO FROM DUAL;
END;
/

CREATE INDEX IX_MUNI_DEPTO ON MUNICIPIO (DEPARTAMENTO_ID_DEPARTAMENTO);
CREATE INDEX IX_REG_MUNI ON REGISTRO (MUNICIPIO_ID_MUNICIPIO);
CREATE INDEX IX_REG_DEPTO ON REGISTRO (MUNICIPIO_DEPARTAMENTO_ID_DEPARTAMENTO);
CREATE INDEX IX_EXA_CORR ON EXAMEN (CORRELATIVO_ID_CORRELATIVO);
CREATE INDEX IX_RU_PREG  ON RESPUESTA_USUARIO (PREGUNTA_ID_PREGUNTA);
CREATE INDEX IX_RU_EXA   ON RESPUESTA_USUARIO (EXAMEN_ID_EXAMEN);
CREATE INDEX IX_RP_PREG  ON RESPUESTA_PRACTICO_USUARIO (PREGUNTA_PRACTICO_ID_PREGUNTA_PRACTICO);
CREATE INDEX IX_RP_EXA   ON RESPUESTA_PRACTICO_USUARIO (EXAMEN_ID_EXAMEN);
