WHENEVER SQLERROR CONTINUE;

-- Crea APPUSER y da privilegios mínimos (si ya existe, ignora el error)
CREATE USER APPUSER IDENTIFIED BY AppUser123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO APPUSER;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW TO APPUSER;
ALTER USER APPUSER ACCOUNT UNLOCK;
